language: rust
rust: stable
cache: cargo
sudo: false
git:
  depth: 1
before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
script:
  - cargo test
  - cargo install -f --debug
  - cargo tidy -c tidy-config.rs.toml
  - cargo tidy -c tidy-config.md.toml
  - cargo tidy -c tidy-config.toml.toml
