# Tidy config for TOML files. Has a weird name because this is the TOML for
# TOML.

include = [ "**/*.toml" ]

# Cargo might copy some TOML files into the target dir, so we exclude them
exclude = [ "target/**" ]

max-line-length = 80

forbidden-content = [
    # This denies Mac OS / Windows line breaks (just "\r" would also work).
    "\\r",
    # This denies all tab characters (just "\t" would also work).
    "\\t",
    # This denies trailing whitespace. We do not use the `\s` whitespace char
    # class since that includes line endings, which we can also match with a
    # regex.
    " $",
]
